-- ======================================================================
-- SETUP NAME : Accounts - Single Use CC Eligibility
-- MAIN TABLE : SUCC_ELIGIBILITY_RULE
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- --- [1] DELETE REMOVED RECORD (Target Only): (NAME=Hotel Mundial) ---
DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 61 AND CODE = 'CO' AND VALUE = 'BAH';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 61 AND CODE = 'CO';

DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 61 AND CODE = 'ACC' AND VALUE = '1173338';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 61 AND CODE = 'ACC';

DELETE FROM SUCC_ELIGIBILITY_RULE WHERE ID = 61;

-- --- [2] UPDATE EXISTING RECORD: (NAME=UAT_SUCC _AMEX) (Target PK: 2) ---
DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 2 AND CODE = 'CO' AND VALUE = 'BAH';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 2 AND CODE = 'CO';

DELETE FROM SUCC_H2H_SOURCES WHERE RULE_ID = 2 AND CODE = '81';

UPDATE SUCC_ELIGIBILITY_RULE
SET PAYMENT_METHOD = 'CardBookingPay', NAME = 'UAT_SUCC _AMEX', DESCRIPTION = 'vPayment for DHISCO in UAT', PRIORITY = 99, PROVIDER = 'AMEX', OFFSET = 3, TBX_ENABLED = 1, RATE_CATEGORY = 'NRF', LAST_MODIFIED_TIME = SYSDATE
WHERE ID = 2;

INSERT INTO SUCC_ELIGIBILITY_RULE_DETAIL (RULE_ID, CODE, NAME, TYPE, APPLICABLE)
VALUES (2, 'CO', 'Company', 'TEXT', 1);

INSERT INTO SUCC_ELIGIBILITY_RULE_VALUE (RULE_ID, CODE, VALUE)
VALUES (2, 'CO', 'BAH');

INSERT INTO SUCC_H2H_SOURCES (RULE_ID, CODE)
VALUES (2, 81);

-- --- [2] UPDATE EXISTING RECORD: (NAME=UAT_SUCC _AMEX_FLEX) (Target PK: 21) ---
DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 21 AND CODE = 'CO' AND VALUE = 'BAH';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 21 AND CODE = 'CO';

DELETE FROM SUCC_H2H_SOURCES WHERE RULE_ID = 21 AND CODE = '81';

UPDATE SUCC_ELIGIBILITY_RULE
SET PAYMENT_METHOD = 'CardBookingPay', NAME = 'UAT_SUCC _AMEX_FLEX', DESCRIPTION = 'vPayment for DHISCO in UAT', PRIORITY = 98, PROVIDER = 'AMEX', OFFSET = 3, TBX_ENABLED = 1, RATE_CATEGORY = 'NOR', LAST_MODIFIED_TIME = SYSDATE
WHERE ID = 21;

INSERT INTO SUCC_ELIGIBILITY_RULE_DETAIL (RULE_ID, CODE, NAME, TYPE, APPLICABLE)
VALUES (21, 'CO', 'Company', 'TEXT', 1);

INSERT INTO SUCC_ELIGIBILITY_RULE_VALUE (RULE_ID, CODE, VALUE, DISPLAY_VALUE)
VALUES (21, 'CO', 'BAH', 'BAH');

INSERT INTO SUCC_H2H_SOURCES (RULE_ID, CODE)
VALUES (21, 81);

-- --- [2] UPDATE EXISTING RECORD: (NAME=SUCC_AMEX_LOCAL_FLEX) (Target PK: 41) ---
DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 41 AND CODE = 'ACC' AND VALUE = '1173573';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 41 AND CODE = 'ACC';

UPDATE SUCC_ELIGIBILITY_RULE
SET PAYMENT_METHOD = 'CardCheckInPay', NAME = 'SUCC_AMEX_LOCAL_FLEX', DESCRIPTION = 'vPayment for flexible local hotel contracts.    New hotels to be added to the "Accommodation" rule parameters.', PRIORITY = 99, PROVIDER = 'AMEX', OFFSET = 0, TBX_ENABLED = 1, RATE_CATEGORY = 'NOR', LAST_MODIFIED_TIME = SYSDATE
WHERE ID = 41;

INSERT INTO SUCC_ELIGIBILITY_RULE_DETAIL (RULE_ID, CODE, NAME, TYPE, APPLICABLE)
VALUES (41, 'ACC', 'Accommodation', 'TEXT', 1);

INSERT INTO SUCC_ELIGIBILITY_RULE_VALUE (RULE_ID, CODE, VALUE, DISPLAY_VALUE)
VALUES (41, 'ACC', '1173338', 'TRIEAN527390 / Hotel Mundial');

-- --- [2] UPDATE EXISTING RECORD: (NAME=SUCC_AMEX_LOCAL_NRF) (Target PK: 42) ---
DELETE FROM SUCC_ELIGIBILITY_RULE_VALUE WHERE RULE_ID = 42 AND CODE = 'ACC' AND VALUE = '1173573';

DELETE FROM SUCC_ELIGIBILITY_RULE_DETAIL WHERE RULE_ID = 42 AND CODE = 'ACC';

UPDATE SUCC_ELIGIBILITY_RULE
SET PAYMENT_METHOD = 'CardBookingPay', NAME = 'SUCC_AMEX_LOCAL_NRF', DESCRIPTION = 'vPayment for non-refundable local contract hotels.  New properties to be added to the "Accommodation" rule paramters.', PRIORITY = 99, PROVIDER = 'AMEX', OFFSET = 0, TBX_ENABLED = 1, RATE_CATEGORY = 'NRF', LAST_MODIFIED_TIME = SYSDATE
WHERE ID = 42;

INSERT INTO SUCC_ELIGIBILITY_RULE_DETAIL (RULE_ID, CODE, NAME, TYPE, APPLICABLE)
VALUES (42, 'ACC', 'Accommodation', 'TEXT', 1);

INSERT INTO SUCC_ELIGIBILITY_RULE_VALUE (RULE_ID, CODE, VALUE, DISPLAY_VALUE)
VALUES (42, 'ACC', '1173338', 'TRIEAN527390 / Hotel Mundial');

