-- ======================================================================
-- SETUP NAME : Calculation Scheme - Type X
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      DISABLE AFFECTED TRIGGERS                        
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME DISABLE;
ALTER TRIGGER TU_CALC_SCHEME DISABLE;
ALTER TRIGGER AUD_CALC_RULE_BRAND DISABLE;
ALTER TRIGGER LMT_CALC_RULE_BRAND DISABLE;
ALTER TRIGGER AUD_CALC_RULE_COMPANY DISABLE;
ALTER TRIGGER LMT_CALC_RULE_COMPANY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_DIST_CH DISABLE;
ALTER TRIGGER LMT_CALC_RULE_DIST_CHANNEL DISABLE;
ALTER TRIGGER AUD_CALC_RULE_DIVISION DISABLE;
ALTER TRIGGER LMT_CALC_RULE_DIVISION DISABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_PROD_CMB DISABLE;
ALTER TRIGGER LMT_CALC_RULE_PRODCOMBINATION DISABLE;
ALTER TRIGGER AUD_CALC_RULE_SOURCE_MARKET DISABLE;
ALTER TRIGGER LMT_CALC_RULE_SOURCE_MARKET DISABLE;
ALTER TRIGGER AUD_CALC_RULE_CITY DISABLE;
ALTER TRIGGER LMT_CALC_RULE_CITY DISABLE;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=TRANSFERS, SCHEME_TYPE=X) ---
DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48170;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=H2H_CARS, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48250;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48250 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48250;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=CASTLEMOCK_Transfer, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'B3' AND SCHEME_ID = 48390;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'C' AND SCHEME_ID = 48390;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'D' AND SCHEME_ID = 48390;

DELETE FROM CALC_RULE_DIVISION WHERE CODE = 'BA' AND SCHEME_ID = 48390;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48390 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48390 AND RULE_TYPE = 'DC';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48390 AND RULE_TYPE = 'DI';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48390;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=SSP_FLT, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48090;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48090;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48090;

DELETE FROM CALC_RULE_DIVISION WHERE CODE = 'BA' AND SCHEME_ID = 48090;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48090 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48090 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48090 AND RULE_TYPE = 'DI';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48090;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=SSP_FLT_MOCK, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'B3' AND SCHEME_ID = 48230;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48230;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48230 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48230 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48230;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=CG_UAT_OPENJAWTG, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48210;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48210;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48210;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'O' AND SCHEME_ID = 48210;

DELETE FROM CALC_RULE_DIVISION WHERE CODE = 'BA' AND SCHEME_ID = 48210;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48210 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48210 AND RULE_TYPE = 'DI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48210 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48210 AND RULE_TYPE = 'DC';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48210;

-- --- [1] DELETE REMOVED RECORD (Target Only): (SCHME_NAME=NDC JUMPSEAT, SCHEME_TYPE=X) ---
DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48033;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48033 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME WHERE SCHEME_ID = 48033;

-- --- [2] UPDATE EXISTING RECORD: (SCHME_NAME=CASTLEMOCK, SCHEME_TYPE=X) (Target PK: 47337) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'B3' AND SCHEME_ID = 47337;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'C' AND SCHEME_ID = 47337;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'D' AND SCHEME_ID = 47337;

DELETE FROM CALC_RULE_DIVISION WHERE CODE = 'BA' AND SCHEME_ID = 47337;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47337 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47337 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47337 AND RULE_TYPE = 'DC';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47337 AND RULE_TYPE = 'DI';

UPDATE CALC_SCHEME
SET SCHME_NAME = 'CASTLEMOCK', SCHEME_DESCRIPTION = 'MOCK SSP : Do not Change', SCHEME_PRIORITY = 999, CALC_RULES = 'CRBR,CRCO,CRDC,CRDI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'X', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47337;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47337, 'B3', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'C', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'D', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'H', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'O', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'S', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47337, 'BA', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47337, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47337, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47337, 'DC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47337, 'DI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=CG_TRANFERS, SCHEME_TYPE=X) (Assigned New PK: 48864) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'CG_TRANFERS', 'Transfers', 1, '', 1, 'X', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=BA_FLT, SCHEME_TYPE=X) (Assigned New PK: 48865) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'BA_FLT', 'SSP set up for flight options yield testing - do not amend', 998, 'CRBR,CRCM,CRCO,CRDI,CRSM,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48865, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48865, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48865, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48865, 'BA', SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48865, 1, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48865, 3, SYSDATE);

INSERT INTO CALC_RULE_SOURCE_MARKET (SCHEME_ID, SOURCE_MARKET, LAST_MODIFIED_TIME)
VALUES (48865, 'GB', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'CM', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'DI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'SM', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=FLT_NDC_MOCK, SCHEME_TYPE=X) (Assigned New PK: 48866) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'FLT_NDC_MOCK', 'FLT_NDC_MOCK', 999, 'CRBR,CRCO,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48866, 'B3', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48866, 'BAH', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'CO', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=HTL_CLUSTER_MOCK, SCHEME_TYPE=X) (Assigned New PK: 48867) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'HTL_CLUSTER_MOCK', 'This mock is deployed on the STG cluster', 992, 'CRBR,CRCO,CRDC,CRDI,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48867, 'B3', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'C', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'D', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'H', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'O', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'S', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'BA', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'DC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'DI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=FLT_CLUSTER_MOCK, SCHEME_TYPE=X) (Assigned New PK: 48868) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 'FLT_CLUSTER_MOCK', 'This mock is deployed on the STG cluster', 992, 'CRBR,CRCO,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48868, 'B3', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48868, 'BAH', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 'CO', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=CG_CARS, SCHEME_TYPE=X) (Assigned New PK: 48869) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48869, 'CG_CARS', 'This SSP rule is set to sort car results by price', 100, '', 1, 'X', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (SCHME_NAME=CG_UAT, SCHEME_TYPE=X) (Target PK: 47194) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'C' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'D' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'H' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_DIST_CHANNEL WHERE CODE = 'S' AND SCHEME_ID = 47194;

DELETE FROM CALC_RULE_DIVISION WHERE CODE = 'BA' AND SCHEME_ID = 47194;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47194 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47194 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47194 AND RULE_TYPE = 'DC';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47194 AND RULE_TYPE = 'DI';

UPDATE CALC_SCHEME
SET SCHME_NAME = 'CG_UAT', SCHEME_DESCRIPTION = 'Created by CG team to provide UAT support', SCHEME_PRIORITY = 995, CALC_RULES = 'CRBR,CRCO,CRDC,CRDI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'X', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47194;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47194, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47194, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'C', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'D', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'H', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'S', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47194, 'BA', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47194, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47194, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47194, 'DC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47194, 'DI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=FLT_SPP_STAGING, SCHEME_TYPE=X) (Assigned New PK: 48870) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48870, 'FLT_SPP_STAGING', 'SPP to determine flight order using priority of Flight priority set up', 50, 'CRBR,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48870, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48870, 'BAL', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48870, 'BR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (SCHME_NAME=CG_UAT_COPY, SCHEME_TYPE=X) (Target PK: 47497) ---
UPDATE CALC_SCHEME
SET SCHME_NAME = 'CG_UAT_COPY', SCHEME_DESCRIPTION = 'Created by CG team to provide UAT support', SCHEME_PRIORITY = 998, CALC_RULES = 'CRBR,CRCI,CRDC,CRDI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'X', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47497;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47497, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47497, 'B3', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (47497, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'ROM', SYSDATE);

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'PAR', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'C', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'D', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'H', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'S', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47497, 'BA', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47497, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47497, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47497, 'DC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47497, 'DI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (SCHME_NAME=TRS_CASTLEMOCK, SCHEME_TYPE=X) (Assigned New PK: 48871) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHME_NAME, SCHEME_DESCRIPTION, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'TRS_CASTLEMOCK', 'TRS_CASTLEMOCK: Do not Change', 999, 'CRBR,CRCO,CRDC,CRDI,CSRP', 1, 'X', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48871, 'B3', SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'C', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'D', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'H', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'O', SYSDATE);

INSERT INTO CALC_RULE_DIST_CHANNEL (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'S', SYSDATE);

INSERT INTO CALC_RULE_DIVISION (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48871, 'BA', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'DC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'DI', SYSDATE);

-- ======================================================================
--                      RE-ENABLE TRIGGERS                              
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME ENABLE;
ALTER TRIGGER TU_CALC_SCHEME ENABLE;
ALTER TRIGGER AUD_CALC_RULE_BRAND ENABLE;
ALTER TRIGGER LMT_CALC_RULE_BRAND ENABLE;
ALTER TRIGGER AUD_CALC_RULE_COMPANY ENABLE;
ALTER TRIGGER LMT_CALC_RULE_COMPANY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_DIST_CH ENABLE;
ALTER TRIGGER LMT_CALC_RULE_DIST_CHANNEL ENABLE;
ALTER TRIGGER AUD_CALC_RULE_DIVISION ENABLE;
ALTER TRIGGER LMT_CALC_RULE_DIVISION ENABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_PROD_CMB ENABLE;
ALTER TRIGGER LMT_CALC_RULE_PRODCOMBINATION ENABLE;
ALTER TRIGGER AUD_CALC_RULE_SOURCE_MARKET ENABLE;
ALTER TRIGGER LMT_CALC_RULE_SOURCE_MARKET ENABLE;
ALTER TRIGGER AUD_CALC_RULE_CITY ENABLE;
ALTER TRIGGER LMT_CALC_RULE_CITY ENABLE;

