-- ======================================================================
-- SETUP NAME : Calculation Scheme - Type X
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      ROLLBACK SCRIPT                                 
-- ======================================================================
-- Run these statements IF YOU NEED TO UNDO the applied changes:

-- Step 1: Clean up current modified tables (children first)
DELETE FROM CALC_RULE_CITY;
DELETE FROM CALC_RULE_SOURCE_MARKET;
DELETE FROM CALC_RULE_PROD_COMBINATION;
DELETE FROM CALC_SCHEME_RULE_PRIORITY;
DELETE FROM CALC_RULE_DIVISION;
DELETE FROM CALC_RULE_DIST_CHANNEL;
DELETE FROM CALC_RULE_COMPANY;
DELETE FROM CALC_RULE_BRAND;
DELETE FROM CALC_SCHEME;

-- Step 2: Restore data from backup tables
INSERT INTO CALC_SCHEME SELECT * FROM B_CALC_SCHEME;
INSERT INTO CALC_RULE_BRAND SELECT * FROM B_CALC_RULE_BRAND;
INSERT INTO CALC_RULE_COMPANY SELECT * FROM B_CALC_RULE_COMPANY;
INSERT INTO CALC_RULE_DIST_CHANNEL SELECT * FROM B_CALC_RULE_DIST_CHANNEL;
INSERT INTO CALC_RULE_DIVISION SELECT * FROM B_CALC_RULE_DIVISION;
INSERT INTO CALC_SCHEME_RULE_PRIORITY SELECT * FROM B_CALC_SCHEME_RULE_PRIORITY;
INSERT INTO CALC_RULE_PROD_COMBINATION SELECT * FROM B_CALC_RULE_PROD_COMBINATION;
INSERT INTO CALC_RULE_SOURCE_MARKET SELECT * FROM B_CALC_RULE_SOURCE_MARKET;
INSERT INTO CALC_RULE_CITY SELECT * FROM B_CALC_RULE_CITY;

-- Step 3: Drop backup tables after restoration
DROP TABLE B_CALC_SCHEME PURGE;
DROP TABLE B_CALC_RULE_BRAND PURGE;
DROP TABLE B_CALC_RULE_COMPANY PURGE;
DROP TABLE B_CALC_RULE_DIST_CHANNEL PURGE;
DROP TABLE B_CALC_RULE_DIVISION PURGE;
DROP TABLE B_CALC_SCHEME_RULE_PRIORITY PURGE;
DROP TABLE B_CALC_RULE_PROD_COMBINATION PURGE;
DROP TABLE B_CALC_RULE_SOURCE_MARKET PURGE;
DROP TABLE B_CALC_RULE_CITY PURGE;
