-- ======================================================================
-- SETUP NAME : Document - Document Rules
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      DISABLE AFFECTED TRIGGERS                        
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME DISABLE;
ALTER TRIGGER TU_CALC_SCHEME DISABLE;
ALTER TRIGGER AUD_CALC_DOCUMENT_SC DISABLE;
ALTER TRIGGER LMT_CALC_DOCUMENT_SCHEME DISABLE;
ALTER TRIGGER AUD_CALC_RULE_BKG_ITEM_STATUS DISABLE;
ALTER TRIGGER LMT_CALC_RULE_BKG_ITEM_STATUS DISABLE;
ALTER TRIGGER AUD_CALC_RULE_BKG_STATUS DISABLE;
ALTER TRIGGER LMT_CALC_RULE_BKG_STATUS DISABLE;
ALTER TRIGGER AUD_CALC_RULE_COMPANY DISABLE;
ALTER TRIGGER LMT_CALC_RULE_COMPANY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_OPTION_STATUS DISABLE;
ALTER TRIGGER LMT_CALC_RULE_OPTION_STATUS DISABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_PROD_CMB DISABLE;
ALTER TRIGGER LMT_CALC_RULE_PRODCOMBINATION DISABLE;
ALTER TRIGGER AUD_CALC_RULE_LINK DISABLE;
ALTER TRIGGER LMT_CALC_RULE_LINK DISABLE;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGAMDEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_OFF_AMD_EML_6.7.15.48_Bundles_addons) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 48510;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCNCLEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CANX_EML_6.7.15.51_HTL) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 47235;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGAMDEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_OFF_AMD_EML_6.7.15.47_HTL) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 47236;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCNCLEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CANX_EML_6.7.15.51_Bundles_addons) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 48491;

-- --- [3] INSERT NEW RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=CBKINV, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=CUS_BKG_INV_6.7.10.44_V2.1.4) (Assigned New PK: 48864) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 90, 1, 'D', SYSDATE);

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48864, 'EML', 'CBKINV', 'CUS_BKG_INV_6.7.10.44_V2.1.4', 'html', 1, 0, 0, 0, 'Generates a booking invoice document based on confirmed booking details', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 2000, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 2000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48864, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 500, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48864, 600, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'BIS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'CO', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCONFEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CONF_EML_6.7.15.36_HTL) (Target PK: 48190) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48190;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48190 AND ID = 1000;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48190;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48190 AND ID = 600;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48190 AND ID = 500;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 2 AND SCHEME_ID = 48190;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48190 AND RULE_TYPE = 'BIS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48190 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48190 AND RULE_TYPE = 'OS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48190 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 99, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48190;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48190, 'EML', 'BKGCONFEMAIL', 'BKG_CONF_EML_6.7.15.36_HTL', 'html', 0, 0, 0, 1, 'Sends a booking confirmation email with customer and booking details after booking is confirmed- Hotel only', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48190, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48190, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48190, 600, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48190, 2, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48190, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48190, 'BIS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48190, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48190, 'CM', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCNCLEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CANX_EML_6.7.10.47_V3.1.5) (Assigned New PK: 48865) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 99, 1, 'D', SYSDATE);

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48865, 'EML', 'BKGCNCLEMAIL', 'BKG_CANX_EML_6.7.10.47_V3.1.5', 'html', 0, 0, 0, 1, 'Hotel Only- The Booking Cancellation Document Rule defines the standardized procedures and conditions under which a booking cancellation is processed.', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48865, 2000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48865, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48865, 500, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48865, 600, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48865, 2, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 'CM', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGAMDEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_OFF_AMD_EML_6.7.15.46_HTL) (Assigned New PK: 48866) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 90, 1, 'D', SYSDATE);

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48866, 'EML', 'BKGAMDEMAIL', 'BKG_OFF_AMD_EML_6.7.15.46_HTL', 'html', 0, 0, 0, 1, 'The Booking Amendment Document Rule specifies the structure and control mechanisms governing changes to confirmed bookings.', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48866, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48866, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48866, 2, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 'CM', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=SUPNOACC, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=SUP_NOTI_ACM_VCC_6.7.10.52_V3) (Target PK: 48755) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48755;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 1000;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 2000;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 4000;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48755 AND ID = 1000;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48755 AND ID = 2000;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_LINK WHERE ID = 1 AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 2 AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 1 AND SCHEME_ID = 48755;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'LI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'BIS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'BS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 99, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48755;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, SUPPLIER_CON_CAT, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48755, 'EML', 'SUPNOACC', 'SUP_NOTI_ACM_VCC_6.7.10.52_V3', 'html', 0, 0, 'R', 0, 1, 'VCC update notification for H2H Hotels', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48755, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 81, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 83, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 78, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 89, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 74, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 79, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 82, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 80, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48755, 1, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48755, 2, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'BIS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'LI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'CM', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCONFEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CONF_EML_6.7.15.51.1_Bundles_addons) (Target PK: 48490) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48490;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48490 AND ID = 1000;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48490;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48490 AND ID = 500;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48490 AND ID = 600;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48490 AND RULE_TYPE = 'BS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48490 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48490 AND RULE_TYPE = 'OS';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 98, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48490;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48490, 'EML', 'BKGCONFEMAIL', 'BKG_CONF_EML_6.7.15.51.1_Bundles_addons', 'html', 0, 0, 0, 1, 'Sends a booking confirmation email with customer and booking details after booking is confirmed - flight + hotel bundles + with/without Transfers', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48490, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48490, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48490, 600, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48490, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48490, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48490, 'BIS', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=TRANSFERVOUCHER, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=TRS_VOUCHER_6.7.15.52_V1.6) (Target PK: 48650) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48650;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48650 AND ID = 1000;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 6 AND SCHEME_ID = 48650;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 8 AND SCHEME_ID = 48650;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48650 AND RULE_TYPE = 'BS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48650 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 1, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48650;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48650, 'EML', 'TRANSFERVOUCHER', 'TRS_VOUCHER_6.7.15.52_V1.6', 'pdf', 0, 0, 1, 0, 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48650, 1000, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48650, 400, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48650, 500, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48650, 600, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48650, 5, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48650, 6, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48650, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48650, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48650, 'CM', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGCNCLEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_CANX_EML_6.7.15.46_Bundles_addons) (Assigned New PK: 48867) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 98, 1, 'D', SYSDATE);

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48867, 'EML', 'BKGCNCLEMAIL', 'BKG_CANX_EML_6.7.15.46_Bundles_addons', 'html', 0, 0, 0, 1, 'The Booking Cancellation Document Rule defines the standardized procedures and conditions under which a booking cancellation is processed.(FLT + HTL Bundle + with/without transfer)', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48867, 2000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48867, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48867, 500, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48867, 600, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 'OS', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=ATOLCERTIFICATE, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=ATOL_Certificate - V2.4) (Target PK: 48450) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48450;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48450 AND ID = 1000;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48450;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48450 AND ID = 500;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48450 AND ID = 600;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48450 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48450 AND RULE_TYPE = 'BS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48450 AND RULE_TYPE = 'OS';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 99, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48450;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48450, 'EML', 'ATOLCERTIFICATE', 'ATOL_Certificate - V2.4', 'pdf', 0, 0, 0, 1, 'ATOL Certification for confirmed flights', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48450, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48450, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48450, 600, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48450, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48450, 'OS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48450, 'CO', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BKGAMDEMAIL, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_OFF_AMD_EML_6.7.10.48_V1) (Assigned New PK: 48868) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 88, 1, 'D', SYSDATE);

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48868, 'EML', 'BKGAMDEMAIL', 'BKG_OFF_AMD_EML_6.7.10.48_V1', 'html', 0, 0, 0, 1, 'FLT + HTL Bundles + with/without TRS - Booking Offline Amendment Email', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48868, 1000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48868, 'BAH', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 'CO', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=TRSREFRESHDOC, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=TRS_REFRESH_NOTI_6.7.15.52_V2) (Target PK: 48610) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48610;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 8 AND SCHEME_ID = 48610;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 6 AND SCHEME_ID = 48610;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48610 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 1, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48610;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48610, 'EML', 'TRSREFRESHDOC', 'TRS_REFRESH_NOTI_6.7.15.52_V2', 'html', 0, 0, 0, 1, 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48610, 5, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48610, 6, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48610, 'CM', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=CARVOUCHER, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=CAR_VOUCHER_6.7.15.52.1) (Target PK: 48751) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48751;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 4 AND SCHEME_ID = 48751;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48751 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 100, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48751;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48751, 'EML', 'CARVOUCHER', 'CAR_VOUCHER_6.7.15.52.1', 'pdf', 0, 0, 1, 0, 'Document rule for Car Voucher for Car Addons (Initial Launch)', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=SUPNOACC, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=SUP_NOTI_ACM_VCC_6.7.10.52_V3) (Target PK: 48755) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48755;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 1000;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 2000;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48755 AND ID = 4000;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48755 AND ID = 1000;

DELETE FROM CALC_RULE_BKG_STATUS WHERE SCHEME_ID = 48755 AND ID = 2000;

DELETE FROM CALC_RULE_COMPANY WHERE CODE = 'BAH' AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_LINK WHERE ID = 1 AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 2 AND SCHEME_ID = 48755;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 1 AND SCHEME_ID = 48755;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'CO';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'LI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'BIS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'BS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48755 AND RULE_TYPE = 'CM';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 99, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48755;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, SUPPLIER_CON_CAT, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48755, 'EML', 'SUPNOACC', 'SUP_NOTI_ACM_VCC_6.7.10.52_V3', 'html', 0, 0, 'R', 0, 1, 'Supplier notification for INHOUSE Contracts', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 2000, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 4000, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 2000, SYSDATE);

INSERT INTO CALC_RULE_COMPANY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48755, 'BAH', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48755, 1, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48755, 2, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48755, 1, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'BIS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'BS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'CO', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'LI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48755, 'CM', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_DOCUMENT_SCHEME.DOC_TYPE=BALANCEPAYMENTRMIND, CALC_DOCUMENT_SCHEME.DOC_TEMPLATE=BKG_BALANCE_DUE_REMINDER_EML_6.7.15.52) (Target PK: 48753) ---
DELETE FROM CALC_DOCUMENT_SCHEME WHERE SCHEME_ID = 48753;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48753 AND ID = 1000;

DELETE FROM CALC_RULE_BKG_ITEM_STATUS WHERE SCHEME_ID = 48753 AND ID = 4000;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48753 AND ID = 500;

DELETE FROM CALC_RULE_OPTION_STATUS WHERE SCHEME_ID = 48753 AND ID = 400;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 3 AND SCHEME_ID = 48753;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 1 AND SCHEME_ID = 48753;

DELETE FROM CALC_RULE_PROD_COMBINATION WHERE COMBINATION_ID = 2 AND SCHEME_ID = 48753;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48753 AND RULE_TYPE = 'CM';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48753 AND RULE_TYPE = 'BIS';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48753 AND RULE_TYPE = 'OS';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 90, CALC_RULES = NULL, STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'D', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48753;

INSERT INTO CALC_DOCUMENT_SCHEME (SCHEME_ID, DISPATCH_METHOD, DOC_TYPE, DOC_TEMPLATE, DOC_FORMAT, TIME_TO_SEND, TIME_TO_GENERATE, QUALITY_CHK_REQ, SEND_AUTOMATICALLY, DESCRIPTION, FREQ_TYPE, FREQ_MONTH, FREQ_DAY, FREQ_DAYS, CUSTOMER_CON_CAT, FORTNIGHT_FIRST_DAY, FORTNIGHT_SECOND_DAY, LAST_MODIFIED_TIME)
VALUES (48753, 'EML', 'BALANCEPAYMENTRMIND', 'BKG_BALANCE_DUE_REMINDER_EML_6.7.15.52', 'html', 0, 0, 0, 0, 'Balance Reminder mail for deposit bookings with a Balance due', 'IMM', 0, 0, 0, 0, 0, 0, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48753, 1000, SYSDATE);

INSERT INTO CALC_RULE_BKG_ITEM_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48753, 4000, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48753, 400, SYSDATE);

INSERT INTO CALC_RULE_OPTION_STATUS (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48753, 500, SYSDATE);

INSERT INTO CALC_RULE_PROD_COMBINATION (SCHEME_ID, COMBINATION_ID, LAST_MODIFIED_TIME)
VALUES (48753, 1, SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48753, 'CM', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48753, 'BIS', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48753, 'OS', SYSDATE);

-- ======================================================================
--                      RE-ENABLE TRIGGERS                              
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME ENABLE;
ALTER TRIGGER TU_CALC_SCHEME ENABLE;
ALTER TRIGGER AUD_CALC_DOCUMENT_SC ENABLE;
ALTER TRIGGER LMT_CALC_DOCUMENT_SCHEME ENABLE;
ALTER TRIGGER AUD_CALC_RULE_BKG_ITEM_STATUS ENABLE;
ALTER TRIGGER LMT_CALC_RULE_BKG_ITEM_STATUS ENABLE;
ALTER TRIGGER AUD_CALC_RULE_BKG_STATUS ENABLE;
ALTER TRIGGER LMT_CALC_RULE_BKG_STATUS ENABLE;
ALTER TRIGGER AUD_CALC_RULE_COMPANY ENABLE;
ALTER TRIGGER LMT_CALC_RULE_COMPANY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_OPTION_STATUS ENABLE;
ALTER TRIGGER LMT_CALC_RULE_OPTION_STATUS ENABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_PROD_CMB ENABLE;
ALTER TRIGGER LMT_CALC_RULE_PRODCOMBINATION ENABLE;
ALTER TRIGGER AUD_CALC_RULE_LINK ENABLE;
ALTER TRIGGER LMT_CALC_RULE_LINK ENABLE;

