-- ======================================================================
-- SETUP NAME : Document - Document Rules
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      ROLLBACK SCRIPT                                 
-- ======================================================================
-- Run these statements IF YOU NEED TO UNDO the applied changes:

-- Step 1: Clean up current modified tables (children first)
DELETE FROM CALC_RULE_LINK;
DELETE FROM CALC_RULE_PROD_COMBINATION;
DELETE FROM CALC_SCHEME_RULE_PRIORITY;
DELETE FROM CALC_RULE_OPTION_STATUS;
DELETE FROM CALC_RULE_COMPANY;
DELETE FROM CALC_RULE_BKG_STATUS;
DELETE FROM CALC_RULE_BKG_ITEM_STATUS;
DELETE FROM CALC_DOCUMENT_SCHEME;
DELETE FROM CALC_SCHEME;

-- Step 2: Restore data from backup tables
INSERT INTO CALC_SCHEME SELECT * FROM B_CALC_SCHEME;
INSERT INTO CALC_DOCUMENT_SCHEME SELECT * FROM B_CALC_DOCUMENT_SCHEME;
INSERT INTO CALC_RULE_BKG_ITEM_STATUS SELECT * FROM B_CALC_RULE_BKG_ITEM_STATUS;
INSERT INTO CALC_RULE_BKG_STATUS SELECT * FROM B_CALC_RULE_BKG_STATUS;
INSERT INTO CALC_RULE_COMPANY SELECT * FROM B_CALC_RULE_COMPANY;
INSERT INTO CALC_RULE_OPTION_STATUS SELECT * FROM B_CALC_RULE_OPTION_STATUS;
INSERT INTO CALC_SCHEME_RULE_PRIORITY SELECT * FROM B_CALC_SCHEME_RULE_PRIORITY;
INSERT INTO CALC_RULE_PROD_COMBINATION SELECT * FROM B_CALC_RULE_PROD_COMBINATION;
INSERT INTO CALC_RULE_LINK SELECT * FROM B_CALC_RULE_LINK;

-- Step 3: Drop backup tables after restoration
DROP TABLE B_CALC_SCHEME PURGE;
DROP TABLE B_CALC_DOCUMENT_SCHEME PURGE;
DROP TABLE B_CALC_RULE_BKG_ITEM_STATUS PURGE;
DROP TABLE B_CALC_RULE_BKG_STATUS PURGE;
DROP TABLE B_CALC_RULE_COMPANY PURGE;
DROP TABLE B_CALC_RULE_OPTION_STATUS PURGE;
DROP TABLE B_CALC_SCHEME_RULE_PRIORITY PURGE;
DROP TABLE B_CALC_RULE_PROD_COMBINATION PURGE;
DROP TABLE B_CALC_RULE_LINK PURGE;
