-- ======================================================================
-- SETUP NAME : Finance - Local Fee Schemes
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      DISABLE AFFECTED TRIGGERS                        
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME DISABLE;
ALTER TRIGGER TU_CALC_SCHEME DISABLE;
ALTER TRIGGER AUD_CALC_RULE_CITY DISABLE;
ALTER TRIGGER LMT_CALC_RULE_CITY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_STAR_RATING DISABLE;
ALTER TRIGGER LMT_CALC_RULE_STAR_RATING DISABLE;
ALTER TRIGGER AUD_CALC_SC_FEES_AND_TAXES DISABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY DISABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY DISABLE;
ALTER TRIGGER AUD_CALC_RULE_BRAND DISABLE;
ALTER TRIGGER LMT_CALC_RULE_BRAND DISABLE;
ALTER TRIGGER AUD_CALC_RULE_STATE DISABLE;
ALTER TRIGGER AUD_CALC_RULE_SUPP DISABLE;
ALTER TRIGGER LMT_CALC_RULE_SUPPLIER DISABLE;
ALTER TRIGGER AUD_CALC_RULE_LINK DISABLE;
ALTER TRIGGER LMT_CALC_RULE_LINK DISABLE;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax All CH, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 47858;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax ALL AD, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 47859;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Environment Fee Any , CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF EF) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 47864;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=TEST, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF AP) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 48373;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Resort Fee, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 48311;

-- --- [1] DEACTIVATE / UPDATE REMOVED RECORD (Target Only): (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=TEST, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF MF) ---
UPDATE CALC_SCHEME
SET ACTIVE = 0
WHERE SCHEME_ID = 48410;

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47582) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47582;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47582;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47582;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47582;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47582;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47582;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47582 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47582 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 0, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47582;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47582, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47582, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47582, 2.5, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47582, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47582, 1, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47582, 'Tourism Tax', 'PLF TT', 'PN', 7, 0, 0, 'EUR', 'A', 5.7);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47582, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47582, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE YA 3, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47861) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47861;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47861;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47861;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47861;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47861 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47861 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47861;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47861, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47861, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47861, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47861, 'Tourism Tax VCE YA 3', 'PLF TT', 'PN', 5, 10, 16, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 1.75);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47861, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47861, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE CH 3 , CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47862) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47862;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47862;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47862;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47862;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47862 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47862 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47862;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47862, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47862, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47862, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47862, 'Tourism Tax VCE CH 3', 'PLF TT', 'PN', 5, 0, 9, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47862, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47862, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE YA 5, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47867) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47867;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47867;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47867;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47867 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47867 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47867;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47867, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47867, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47867, 'Tourism Tax VCE YA 5', 'PLF TT', 'PN', 5, 10, 16, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 2.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47867, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47867, 'SR', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism tax, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Assigned New PK: 48864) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 10, 'CRCI,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48864, 'LIS', SYSDATE);

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48864, 'CPT', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48864, 'Tourism tax', 'PLF TT', 'PN', 7, 13, 100, 'EUR', 'A', 4);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48864, 'CI', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE YA 2 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47870) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47870;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47870;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47870;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47870;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47870;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47870 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47870 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47870;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47870, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47870, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47870, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47870, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47870, 'Tourism Tax VCE YA 2 YR', 'PLF TT', 'PN', 5, 10, 16, 'EUR', 'A', 0.7);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47870, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47870, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE CH 2 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47871) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47871;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47871;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47871;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47871;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47871;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47871 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47871 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47871;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47871, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47871, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47871, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47871, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47871, 'Tourism Tax VCE CH 2 YR', 'PLF TT', 'PN', 5, 0, 9, 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47871, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47871, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD 3 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47873) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47873;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47873;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47873;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47873;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47873 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47873 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47873;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47873, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47873, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47873, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47873, 'Tourism Tax VCE AD 3 YR', 'PLF TT', 'PN', 5, 17, 100, 'EUR', 'A', 2.4);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47873, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47873, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE CH 3  YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47874) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47874;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47874;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47874;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47874;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47874 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47874 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47874;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47874, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47874, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47874, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47874, 'Tourism Tax VCE CH 3  YR', 'PLF TT', 'PN', 5, 0, 9, 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47874, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47874, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD5 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47879) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47879;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47879;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47879;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47879 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47879 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47879;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47879, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47879, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47879, 'Tourism Tax VCE AD5 YR', 'PLF TT', 'PN', 5, 17, 100, 'EUR', 'A', 3.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47879, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47879, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE CH 5 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47880) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47880;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47880;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47880;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47880 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47880 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47880;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47880, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47880, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47880, 'Tourism Tax VCE CH 5 YR', 'PLF TT', 'PN', 5, 0, 9, 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47880, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47880, 'SR', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax ALL, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Assigned New PK: 48865) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48865, 60, '', 0, 'L', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48865, 'Tourism Tax ALL', 'PLF TT', 'PN', 7, 0, 100, 'EUR', 'A', 500);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourist Tax, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 48111) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48111;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48111;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48111 AND CODE = 'FR75';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48111;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48111 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48111 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48111;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48111, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48111, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48111, 'FR75', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48111, 'Tourist Tax', 'PLF TT', 'PN', 'EUR', 'A', 20);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48111, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48111, 'STA', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Resort Fee Adult ROM, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) (Target PK: 47797) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'ROM' AND SCHEME_ID = 47797;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47797;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47797 AND RULE_TYPE = 'CI';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 10, CALC_RULES = 'CRCI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47797;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47797, 'ROM', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47797, 'Resort Fee Adult ROM', 'PLF RF', 'PN', 18, 100, 'EUR', 'A', 100);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47797, 'CI', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Resort Fee Child ROM, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) (Target PK: 47798) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'ROM' AND SCHEME_ID = 47798;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47798;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47798 AND RULE_TYPE = 'CI';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 10, CALC_RULES = 'CRCI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47798;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47798, 'ROM', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47798, 'Resort Fee Child ROM', 'PLF RF', 'PN', 10, 17, 'EUR', 'A', 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47798, 'CI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Environmental Fee AD, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF EF) (Assigned New PK: 48866) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48866, 60, '', 0, 'L', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48866, 'Environmental Fee AD', 'PLF EF', 'PN', 18, 100, 'EUR', 'A', 99);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Environmental Fee CH, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF EF) (Assigned New PK: 48867) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48867, 60, '', 1, 'L', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48867, 'Environmental Fee CH', 'PLF EF', 'PN', 0, 17, '31-JUL-25', '30-AUG-25', 'EUR', 'A', 10);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN YA 5, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47922) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47922;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47922;

DELETE FROM CALC_RULE_SUPPLIER WHERE SUPPLIER_ID = 1173285 AND SCHEME_ID = 47922;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47922;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47922 AND RULE_TYPE = 'ACC';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47922 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47922 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CRACC,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47922;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47922, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47922, 5, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173285', 47922, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47922, 'Tourism Tax BCN YA 5', 'PLF TT', 'PN', 5, 10, 16, '31-AUG-25', 'EUR', 'A', 5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47922, 'ACC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47922, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47922, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax MVP C, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 48010) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48010;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48010;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48010 AND CODE = 'FR75';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48010;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48010 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48010 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 20, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48010;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48010, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48010, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48010, 'FR75', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48010, 'Tourism Tax MVP C', 'PLF TT', 'RS', 'EUR', 'P', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48010, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48010, 'STA', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax MVP C, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 48010) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48010;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48010;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48010 AND CODE = 'FR75';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48010;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48010 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48010 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 10, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48010;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48010, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48010, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48010, 'FR75', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48010, 'Tourism Tax MVP C', 'PLF TT', 'RS', 'EUR', 'P', 7.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48010, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48010, 'STA', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax AMS, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47818) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'AMS' AND SCHEME_ID = 47818;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47818;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47818 AND RULE_TYPE = 'CI';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47818;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47818, 'AMS', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47818, 'Tourism Tax AMS', 'PLF TT', 'PN', 7, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 100);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47818, 'CI', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD 3, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47860) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47860;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47860;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47860;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47860;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47860 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47860 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47860;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47860, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47860, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47860, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47860, 'Tourism Tax VCE AD 3', 'PLF TT', 'PN', 5, 17, 100, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 3.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47860, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47860, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD 4, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47863) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47863;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.0' AND SCHEME_ID = 47863;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.5' AND SCHEME_ID = 47863;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47863;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47863 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47863 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47863;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47863, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47863, 4, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47863, 4.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47863, 'Tourism Tax VCE AD 4', 'PLF TT', 'PN', 5, 17, 100, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 4.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47863, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47863, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD5, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47866) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47866;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47866;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47866;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47866 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47866 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47866;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47866, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47866, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47866, 'Tourism Tax VCE AD5', 'PLF TT', 'PN', 5, 17, 100, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47866, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47866, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE AD 2 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47869) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47869;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47869;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47869;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47869;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47869;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47869 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47869 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47869;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47869, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47869, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47869, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47869, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47869, 'Tourism Tax VCE AD 2 YR', 'PLF TT', 'PN', 5, 17, 100, 'EUR', 'A', 1.4);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47869, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47869, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE YA 4 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47875) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47875;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.0' AND SCHEME_ID = 47875;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.5' AND SCHEME_ID = 47875;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47875;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47875 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47875 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47875;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47875, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47875, 4, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47875, 4.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47875, 'Tourism Tax VCE YA 4 YR', 'PLF TT', 'PN', 5, 10, 16, 'EUR', 'A', 1.55);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47875, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47875, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax VCE YA 5 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47878) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'VCE' AND SCHEME_ID = 47878;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47878;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47878;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47878 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47878 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47878;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47878, 'VCE', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47878, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47878, 'Tourism Tax VCE YA 5 YR', 'PLF TT', 'PN', 5, 10, 16, 'EUR', 'A', 1.75);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47878, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47878, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN YA 2, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47897) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47897;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47897;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47897;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47897;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47897;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47897 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47897 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47897;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47897, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47897, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47897, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47897, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47897, 'Tourism Tax BCN YA 2', 'PLF TT', 'PN', 5, 10, 16, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 1);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47897, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47897, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN CH 2, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47898) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47898;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47898;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47898;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47898;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47898;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47898 AND RULE_TYPE = 'SR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47898 AND RULE_TYPE = 'CI';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47898;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47898, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47898, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47898, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47898, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47898, 'Tourism Tax BCN CH 2', 'PLF TT', 'PN', 5, 0, 9, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47898, 'SR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47898, 'CI', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN YA 4, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47901) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47901;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.0' AND SCHEME_ID = 47901;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.5' AND SCHEME_ID = 47901;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47901;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47901 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47901 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47901;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47901, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47901, 4, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47901, 4.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47901, 'Tourism Tax BCN YA 4', 'PLF TT', 'PN', 5, 10, 16, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 2.25);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47901, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47901, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN CH 4, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47902) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47902;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.0' AND SCHEME_ID = 47902;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.5' AND SCHEME_ID = 47902;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47902;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47902 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47902 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47902;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47902, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47902, 4, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47902, 4.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47902, 'Tourism Tax BCN CH 4', 'PLF TT', 'PN', 5, 0, 9, '01-AUG-25', '31-AUG-25', 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47902, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47902, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN CH 2 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47906) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47906;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47906;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47906;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47906;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47906;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47906 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47906 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47906;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47906, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47906, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47906, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47906, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47906, 'Tourism Tax BCN CH 2 YR', 'PLF TT', 'PN', 5, 0, 9, '01-SEP-25', 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47906, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47906, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN AD 3 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47907) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47907;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47907;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47907;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47907;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47907 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47907 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 0, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47907;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47907, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47907, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47907, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47907, 'Tourism Tax BCN AD 3 YR', 'PLF TT', 'PN', 5, 17, 100, '01-SEP-25', 'EUR', 'A', 2.4);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47907, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47907, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN CH 3  YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47908) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47908;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.0' AND SCHEME_ID = 47908;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '3.5' AND SCHEME_ID = 47908;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47908;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47908 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47908 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47908;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47908, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47908, 3, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47908, 3.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47908, 'Tourism Tax BCN CH 3  YR', 'PLF TT', 'PN', 5, 0, 9, '01-SEP-25', 'EUR', 'A', 0);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47908, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47908, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN AD5 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47911) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47911;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47911;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47911;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47911 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47911 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47911;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47911, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47911, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47911, 'Tourism Tax BCN AD5 YR', 'PLF TT', 'PN', 5, 17, 100, '01-SEP-25', 'EUR', 'A', 3.5);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47911, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47911, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN AD 2 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47917) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47917;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '1.0' AND SCHEME_ID = 47917;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.0' AND SCHEME_ID = 47917;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '2.5' AND SCHEME_ID = 47917;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47917;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47917 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47917 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47917;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47917, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47917, 1, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47917, 2, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47917, 2.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47917, 'Tourism Tax BCN AD 2 YR', 'PLF TT', 'PN', 5, 17, 100, '01-SEP-25', 'EUR', 'A', 1.4);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47917, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47917, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN YA 4 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47919) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47919;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.0' AND SCHEME_ID = 47919;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '4.5' AND SCHEME_ID = 47919;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47919;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47919 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47919 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47919;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47919, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47919, 4, SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47919, 4.5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47919, 'Tourism Tax BCN YA 4 YR', 'PLF TT', 'PN', 5, 10, 16, '01-SEP-25', 'EUR', 'A', 1.55);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47919, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47919, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax BCN YA 5 YR, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 47920) ---
DELETE FROM CALC_RULE_CITY WHERE CODE = 'BCN' AND SCHEME_ID = 47920;

DELETE FROM CALC_RULE_STAR_RATING WHERE STAR = '5.0' AND SCHEME_ID = 47920;

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 47920;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47920 AND RULE_TYPE = 'CI';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 47920 AND RULE_TYPE = 'SR';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 50, CALC_RULES = 'CRCI,CRSR,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 47920;

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (47920, 'BCN', SYSDATE);

INSERT INTO CALC_RULE_STAR_RATING (SCHEME_ID, STAR, LAST_MODIFIED_TIME)
VALUES (47920, 5, SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, TRAVEL_FROM_DATE, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (47920, 'Tourism Tax BCN YA 5 YR', 'PLF TT', 'PN', 5, 10, 16, '01-SEP-25', 'EUR', 'A', 1.75);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47920, 'CI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (47920, 'SR', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax JUMPSEAT, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 48030) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48030;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48030;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48030 AND CODE = 'FR75';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48030;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48030 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48030 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48030;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48030, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48030, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48030, 'FR75', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48030, 'Tourism Tax JUMPSEAT', 'PLF TT', 'PN', 0, 0, 100, 'EUR', 'A', 20);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48030, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48030, 'STA', SYSDATE);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax JUMPSEAT, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Target PK: 48030) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48030;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48030;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48030 AND CODE = 'FR75';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48030;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48030 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48030 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 60, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48030;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48030, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48030, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48030, 'FR75', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, MAX_NIGHTS, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48030, 'Tourism Tax JUMPSEAT', 'PLF TT', 'PN', 0, 0, 100, 'ZAR', 'A', 100);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48030, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48030, 'STA', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Tourism Tax Test, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) (Assigned New PK: 48868) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48868, 40, '', 1, 'L', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48868, 'Tourism Tax Test', 'PLF RF', 'RN', 'EUR', 'A', 50);

-- --- [2] UPDATE EXISTING RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Service Charge ALC, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF SC) (Target PK: 48130) ---
DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAT' AND SCHEME_ID = 48130;

DELETE FROM CALC_RULE_BRAND WHERE BRAND = 'BAL' AND SCHEME_ID = 48130;

DELETE FROM CALC_RULE_STATE WHERE SCHEME_ID = 48130 AND CODE = 'ESA';

DELETE FROM CALC_SCHEME_FEES_AND_TAXES WHERE SCHEME_ID = 48130;

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48130 AND RULE_TYPE = 'BR';

DELETE FROM CALC_SCHEME_RULE_PRIORITY WHERE SCHEME_ID = 48130 AND RULE_TYPE = 'STA';

UPDATE CALC_SCHEME
SET SCHME_NAME = NULL, SCHEME_DESCRIPTION = NULL, SCHEME_PRIORITY = 10, CALC_RULES = 'CRBR,CRSTA,CSRP', STATUS_ID = NULL, STAGE_NO = NULL, SEARCH_KEY = NULL, ACTIVE = 1, SCHEME_TYPE = 'L', LAST_MODIFIED_TIME = SYSDATE, PACKAGE_PRICING_GROUP_TYPE = NULL, PACKAGE_PRICING_GROUP_APPLIES_AT = NULL
WHERE SCHEME_ID = 48130;

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48130, 'BAT', SYSDATE);

INSERT INTO CALC_RULE_BRAND (SCHEME_ID, BRAND, LAST_MODIFIED_TIME)
VALUES (48130, 'BAL', SYSDATE);

INSERT INTO CALC_RULE_STATE (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48130, 'ESA', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48130, 'Service Charge ALC', 'PLF SC', 'PN', 0, 100, 'EUR', 'A', 999);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48130, 'BR', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48130, 'STA', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Test Additional Fee, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF AP) (Assigned New PK: 48869) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48869, 10, 'CRACC,CSRP', 1, 'L', SYSDATE);

-- INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
-- VALUES ('1173775', 48869, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, ADDITIONAL_PAX, CURRENCY, FEE_APPLICATION, ADULT_AMOUNT, CHILD1_AMOUNT, CHILD2_AGE_FROM, CHILD2_AGE_TO, CHILD2_AMOUNT, INFANT_AMOUNT)
VALUES (48869, 'Test Additional Fee', 'PLF AP', 'PN', 3, 11, 2, 'EUR', 'A', 200, 100, 12, 17, 150, 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48869, 'ACC', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Hotel Mundial (3rd PAX Fee), CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF AP) (Assigned New PK: 48870) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48870, 10, 'CRACC,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173338', 48870, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CHILD1_AGE_FROM, CHILD1_AGE_TO, ADDITIONAL_PAX, TRAVEL_FROM_DATE, TRAVEL_TO_DATE, CURRENCY, FEE_APPLICATION, ADULT_AMOUNT, CHILD1_AMOUNT, CHILD2_AGE_FROM, CHILD2_AGE_TO, CHILD2_AMOUNT, INFANT_AMOUNT)
VALUES (48870, 'Hotel Mundial (3rd PAX Fee)', 'PLF AP', 'PN', 2, 11, 2, '01-JUN-26', '31-DEC-26', 'EUR', 'A', 200, 100, 12, 17, 150, 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48870, 'ACC', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Mondial INHOUSE, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) (Assigned New PK: 48871) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 10, 'CRACC,CRLI,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 81, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 83, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 78, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 74, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 79, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 82, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 80, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48871, 1, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173338', 48871, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48871, 'Mondial INHOUSE', 'PLF RF', 'RN', 'EUR', 'A', 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'LI', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48871, 'ACC', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Mondial DC, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF RF) (Assigned New PK: 48872) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48872, 10, 'CRACC,CRLI,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48872, 1, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173338', 48872, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48872, 'Mondial DC', 'PLF RF', 'RN', 'EUR', 'A', 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48872, 'ACC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48872, 'LI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=DWNCD-958 A, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Assigned New PK: 48873) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48873, 10, 'CRLI,CRACC,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48873, 1, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173773', 48873, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48873, 'DWNCD-958 A', 'PLF TT', 'RN', 'EUR', 'A', 50);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48873, 'ACC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48873, 'LI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=DWNCD-958 B, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Assigned New PK: 48874) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48874, 10, 'CRLI,CRACC,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48874, 1, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173773', 48874, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48874, 'DWNCD-958 B', 'PLF TT', 'RN', 'EUR', 'A', 60);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48874, 'ACC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48874, 'LI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=Liberdade (Test 2), CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF TT) (Assigned New PK: 48875) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48875, 10, 'CRACC,CRLI,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 81, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 83, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 78, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 74, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 79, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 82, SYSDATE);

INSERT INTO CALC_RULE_LINK (SCHEME_ID, ID, LAST_MODIFIED_TIME)
VALUES (48875, 80, SYSDATE);

INSERT INTO CALC_RULE_SUPPLIER (SUPPLIER_ID, SCHEME_ID, SUPPLIER_TYPE, LAST_MODIFIED_TIME)
VALUES ('1173773', 48875, 'A', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, UNIT_AMOUNT)
VALUES (48875, 'Liberdade (Test 2)', 'PLF TT', 'RN', 'EUR', 'A', 49);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48875, 'ACC', SYSDATE);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48875, 'LI', SYSDATE);

-- --- [3] INSERT NEW RECORD: (CALC_SCHEME_FEES_AND_TAXES.FEE_TYPE=CMA Fee, CALC_SCHEME_FEES_AND_TAXES.FEE_CATEGORY=PLF URF) (Assigned New PK: 48876) ---
INSERT INTO CALC_SCHEME (SCHEME_ID, SCHEME_PRIORITY, CALC_RULES, ACTIVE, SCHEME_TYPE, LAST_MODIFIED_TIME)
VALUES (48876, 80, 'CRCI,CSRP', 1, 'L', SYSDATE);

INSERT INTO CALC_RULE_CITY (SCHEME_ID, CODE, LAST_MODIFIED_TIME)
VALUES (48876, 'LIS', SYSDATE);

INSERT INTO CALC_SCHEME_FEES_AND_TAXES (SCHEME_ID, FEE_TYPE, FEE_CATEGORY, FEE_CALC_METHOD, CURRENCY, FEE_APPLICATION, ADULT_AMOUNT)
VALUES (48876, 'CMA Fee', 'PLF URF', 'PN', 'EUR', 'A', 30);

INSERT INTO CALC_SCHEME_RULE_PRIORITY (SCHEME_ID, RULE_TYPE, LAST_MODIFIED_TIME)
VALUES (48876, 'CI', SYSDATE);

-- ======================================================================
--                      RE-ENABLE TRIGGERS                              
-- ======================================================================
ALTER TRIGGER AUD_CALC_SC ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME ENABLE;
ALTER TRIGGER TU_CALC_SCHEME ENABLE;
ALTER TRIGGER AUD_CALC_RULE_CITY ENABLE;
ALTER TRIGGER LMT_CALC_RULE_CITY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_STAR_RATING ENABLE;
ALTER TRIGGER LMT_CALC_RULE_STAR_RATING ENABLE;
ALTER TRIGGER AUD_CALC_SC_FEES_AND_TAXES ENABLE;
ALTER TRIGGER AUD_CALC_SC_RULE_PRIORITY ENABLE;
ALTER TRIGGER LMT_CALC_SCHEME_RULE_PRIORITY ENABLE;
ALTER TRIGGER AUD_CALC_RULE_BRAND ENABLE;
ALTER TRIGGER LMT_CALC_RULE_BRAND ENABLE;
ALTER TRIGGER AUD_CALC_RULE_STATE ENABLE;
ALTER TRIGGER AUD_CALC_RULE_SUPP ENABLE;
ALTER TRIGGER LMT_CALC_RULE_SUPPLIER ENABLE;
ALTER TRIGGER AUD_CALC_RULE_LINK ENABLE;
ALTER TRIGGER LMT_CALC_RULE_LINK ENABLE;

