-- ======================================================================
-- SETUP NAME : Finance - Local Fee Schemes
-- MAIN TABLE : CALC_SCHEME
-- SYNC MODE  : FULL_SYNC
-- ======================================================================

-- ======================================================================
--                      ROLLBACK SCRIPT                                 
-- ======================================================================
-- Run these statements IF YOU NEED TO UNDO the applied changes:

-- Step 1: Clean up current modified tables (children first)
DELETE FROM CALC_RULE_LINK;
DELETE FROM CALC_RULE_SUPPLIER;
DELETE FROM CALC_RULE_STATE;
DELETE FROM CALC_RULE_BRAND;
DELETE FROM CALC_SCHEME_RULE_PRIORITY;
DELETE FROM CALC_SCHEME_FEES_AND_TAXES;
DELETE FROM CALC_RULE_STAR_RATING;
DELETE FROM CALC_RULE_CITY;
DELETE FROM CALC_SCHEME;

-- Step 2: Restore data from backup tables
INSERT INTO CALC_SCHEME SELECT * FROM B_CALC_SCHEME;
INSERT INTO CALC_RULE_CITY SELECT * FROM B_CALC_RULE_CITY;
INSERT INTO CALC_RULE_STAR_RATING SELECT * FROM B_CALC_RULE_STAR_RATING;
INSERT INTO CALC_SCHEME_FEES_AND_TAXES SELECT * FROM B_CALC_SCHEME_FEES_AND_TAXES;
INSERT INTO CALC_SCHEME_RULE_PRIORITY SELECT * FROM B_CALC_SCHEME_RULE_PRIORITY;
INSERT INTO CALC_RULE_BRAND SELECT * FROM B_CALC_RULE_BRAND;
INSERT INTO CALC_RULE_STATE SELECT * FROM B_CALC_RULE_STATE;
INSERT INTO CALC_RULE_SUPPLIER SELECT * FROM B_CALC_RULE_SUPPLIER;
INSERT INTO CALC_RULE_LINK SELECT * FROM B_CALC_RULE_LINK;

-- Step 3: Drop backup tables after restoration
DROP TABLE B_CALC_SCHEME PURGE;
DROP TABLE B_CALC_RULE_CITY PURGE;
DROP TABLE B_CALC_RULE_STAR_RATING PURGE;
DROP TABLE B_CALC_SCHEME_FEES_AND_TAXES PURGE;
DROP TABLE B_CALC_SCHEME_RULE_PRIORITY PURGE;
DROP TABLE B_CALC_RULE_BRAND PURGE;
DROP TABLE B_CALC_RULE_STATE PURGE;
DROP TABLE B_CALC_RULE_SUPPLIER PURGE;
DROP TABLE B_CALC_RULE_LINK PURGE;
